#! /usr/bin/bash

echo Creating config directory...
mkdir configs 2> /dev/null

echo Building configurations...
SEED=(42)
RATIO=(0.0 0.1 0.2 0.3 0.4 0.5)

for s in ${SEED[@]}
do
    for r in ${RATIO[@]}
    do
        echo ... Creating SEED $s RATIO $r...
        python simulation.py --print-config INPUT.SIGNAL.RATIO $r INPUT.MATRIX.SEED $s OUTPUT.OUTPUT_DIR ratio=${r}_seed=${s} >| configs/ratio=${r}_seed=${s}.yaml
    done
done
