OUTPUT:
  OUTPUT_DIR: "strong_signal"
  VIDEO_OUTPUT: True
  DB:
    OUTPUT_FILE: "simulation.sqlite"
    TABLE: "simulation"
INPUT:
  MATRIX:
    ROWS: 5000
    COLUMNS: 4000
    SEED: 42
  SIGNAL:
    RATIO: 0.8
    BY_DET:
      ENABLED: False
      RANK: 2500
    BY_IMG:
      ENABLED: True
      FILE: "tigro.jpeg"
  BINNING:
    BINS: 100
    SMOOTHING: 1.0
  E_SCALE:
    BY_VALUE:
      ENABLED: False
      MIN: 0.22
      MAX: 0.4
    BY_MASS_SCALE:
      ENABLED: False
      WIDTH: 0.25
    BY_ENDPOINT:
      ENABLED: True
      WIDTH: 0.25
      EPSILON: 0.025
      SPIKES: False
  INIT:
    BY_TEMP:
      ENABLED: False
      T: 1.0
      TC: 0.5
    BY_PARAMS:
      ENABLED: False
      MU_0: -1.0
      MU_1: 2.0
      MU_2: 0.0
      MU_3: 0.0
    BY_INIT:
      ENABLED: True
      KAPPA_0: 0.0
      MU_0: 1.0
      MU_1: 1.0
      MU_2: 0.0
SIM:
  INF: 0.0
  SUP: 1.0
  N_VALUES: 1000
  N_STEPS: 1000
  PERIODIC: False
  IR_TO_UV: False
  EIGEN_THRESH: 0.025
